### ISSUE TITLE
Imbunatatire algoritm. Sa nu se afiseze accesi carte una dupa cealalta

### ISSUE THREAD

**Issue by adam-gligor** [forit-brainiacs/flashcards#12]

**Comment by adam-gligor** [comment]
-) Sa se afisieze o singura data fiecare carte din set 
-) O runda se termina cand s-au afisat toate cartile (dupa terminarea rundei se afiseaza pagina de statistica)

**Comment by radusocaci** [comment]
Dupa ce am scris ce ai trimis tu pe mail, in cardSetModule, nu mai merge sa mai dai pe butonul start test deloc. Algoritmul din cardSetModule nu trebuie sa dea fiecare carte numa 1 data pana nu mai are ce da?

**Comment by adam-gligor** [comment]
nu am testat codul ala ... posibil sa nu functioneze chiar asa cum e.
