### ISSUE TITLE
Efect de "flip" la intoarcerea cartilor 

### ISSUE THREAD

**Issue by adam-gligor** [forit-brainiacs/flashcards#14]
Foloseste:  https://nnattawat.github.io/flip/
Pasi de implementare: 

- In learn.cshtml 
     - Sterge referinta la ratchet.js
     - Adauga referinte la jquery.min.js, apoi jquery.flip.min.js (flip.js copiaza-l in solutie)
     - Activeaza efectul cu ... ontouchstart="$('.flash').flip();";
- In style.css, ajustari de css
     -  sterge tot legat de content-flash
     -  adauga .flash{height:100%} si padding dupa preferinta ex. center{padding-top:22px;}

**Comment by radusocaci** [comment]
Am tot incercat, pur si simplu nu merge. Am facut cum ai zis tu, s-a intors odata dupa a

**Comment by radusocaci** [comment]
Am tot incercat, pur si simplu nu merge. Am facut cum ai zis tu, s-a intors odata dupa a inceput sa faca fite iara.. Poate nu sterg eu calumea content-flashu ala, cu toate ca in exemplu la ei totul merge atata de bine si atata de simplu.. Nici cu script d-ala facut acolo (am dat fork la aia) nu merge.. Idk..
