### ISSUE TITLE
Imbunatatire estetica a paginii de rezultat

### ISSUE THREAD

**Issue by adam-gligor** [forit-brainiacs/flashcards#15]
Cateva sugestii dintre care puteti alege: 

- In functie de scor, diferite imagini pentru slab/mediu/bun, sau fete zambitoare, sau stele
- Adaugat mai multe informatii despre set, ex "Testul <Nume set>, <Domeniu set> a luat sfarsit."

**Comment by radusocaci** [comment]
Ce imagini sa pun pentru feature-ul acela de generare a imaginilor in functie de punctajul obtinut?
