### ISSUE TITLE
de organizat lista de carti pe domenii pe pagina home

### ISSUE THREAD

**Issue by adam-gligor** [forit-brainiacs/flashcards#8]

**Comment by adamitrea** [comment]
Atunci trebuie sa scrie domeniul cand se face un set nou de carti??

**Comment by radusocaci** [comment]
Da, inteleg ce spui, dar imaginiile alea pot sa le pui numa pe pagina cu categorii, ca iara ar trb ceva algoritm pentru ca sa le pui dupa numele cursului sau ceva.

**Comment by adam-gligor** [comment]
mai trebuie updatate seturile sa aiba fiecare o categorie
